data_pnd
_2dpd_file_name_bkgr 'full.bkg'
_2dpd_file_name_input 'full.dat'
_2dpd_file_name_output 'full.out'

_2dpd_chi2_up False
_2dpd_chi2_down False
_2dpd_chi2_diff True
_2dpd_chi2_sum False
_2dpd_exl2theta '(60.,90.)'

_2dpd_beam_polarization_up 0.836865522283
_2dpd_beam_polarization_down 0.836865522283

_2dpd_resolution_u 17.4877038937
_2dpd_resolution_v -2.83572490939
_2dpd_resolution_w 0.576309204074
_2dpd_resolution_x 0.0
_2dpd_resolution_y 0.0

_2dpd_shift_const -0.37138377716
_2dpd_shift_coeff 0.0
_2dpd_reflex_asymetry_p1 0.0
_2dpd_reflex_asymetry_p2 0.0
_2dpd_reflex_asymetry_p3 0.0
_2dpd_reflex_asymetry_p4 0.0
_2dpd_tth_min 4.0
_2dpd_tth_max 80.0
_2dpd_phi_min -2.0
_2dpd_phi_max 40.0


loop_
_2dpd_phase_name
_2dpd_phase_scale
_2dpd_phase_igsize
_2dpd_phase_extinction_radius
_2dpd_phase_extinction_mosaicity
 Fe3O4  0.0218424393025  0.0  0.0  0.0

